%% Last updated: 2024-08-01
graph TD
    A[Input] --> |canvas, query, parameters| B[displayTriples.js]
    B --> |Does| C[1.Triple Loading]
    B --> |Does| D[2.Display Style Selection]
    B --> |Does| E[3.Graph Rendering]
    
    C --> |Uses| F[fetch-sparql-endpoint@5.0.0]
    C --> |Uses| G[rdf-object@1.14.0]
    
    E --> |Uses| H[@viz-js/viz@3.6.0]
    
    I[endpoint.js] --> |Provides Endpoint URL| C
    J[helpers.js] --> |Utility Functions| B
    
    E --> |Rendered Graph in HTML| K[canvas]

    style B fill:#4682b4,stroke:#333,stroke-width:4px