graph TD
    A[Input] --> |SPARQL Query & Parameters| B[displayTriples.js]
    B --> |Does| C[1.Triple Loading]
    B --> |Does| D[2.Display Style Selection]
    B --> |Does| E[3.Graph Rendering]
    
    C --> |Uses| F[SparqlEndpointFetcher]
    C --> |Uses| G[RdfObjectLoader]
    
    E --> |Uses| H[viz-js]
    
    I[endpoint.js] --> |Provides Endpoint URL| C
    J[helpers.js] --> |Utility Functions| B
    
    E --> K[Output: Rendered Graph on HTML Canvas]

    style B fill:#4682b4,stroke:#333,stroke-width:4px